# Generated by Django 3.0.1 on 2020-01-07 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('height', models.DecimalField(decimal_places=0, max_digits=3)),
                ('club', models.CharField(max_length=100)),
                ('preferred_foot', models.CharField(choices=[('left', 'Lewa'), ('right', 'Prawa'), ('both', 'Obie')], default='right', max_length=5)),
                ('position', models.CharField(choices=[('ST', 'N'), ('LW', 'LS'), ('RW', 'PS'), ('LM', 'LP'), ('RM', 'PP'), ('CAM', 'ŚPO'), ('CM', 'ŚP'), ('CDM', 'ŚPD'), ('LB', 'LO'), ('RB', 'PO'), ('CB', 'ŚO'), ('GK', 'BR')], default='ST', max_length=3)),
                ('matches_played', models.DecimalField(decimal_places=0, max_digits=3)),
                ('minutes_played', models.DecimalField(decimal_places=0, max_digits=5)),
                ('goals', models.DecimalField(decimal_places=0, max_digits=3)),
                ('assists', models.DecimalField(decimal_places=0, max_digits=3)),
                ('shots_per_game', models.FloatField()),
                ('big_chances_missed', models.DecimalField(decimal_places=0, max_digits=3)),
                ('passes_per_game', models.FloatField()),
                ('accurate_passes_per_game', models.FloatField()),
                ('crosses_per_game', models.FloatField()),
                ('accurate_crosses_per_game', models.FloatField()),
                ('key_passes_per_game', models.FloatField()),
                ('interceptions_per_game', models.FloatField()),
                ('tackles_per_game', models.FloatField()),
                ('possession_won_per_game', models.FloatField()),
                ('dribbled_per_game', models.FloatField()),
                ('clearances_per_game', models.FloatField()),
                ('error_leading_to_goal', models.DecimalField(decimal_places=0, max_digits=3)),
                ('penalty_committed', models.DecimalField(decimal_places=0, max_digits=3)),
                ('dribbles', models.DecimalField(decimal_places=0, max_digits=4)),
                ('successful_dribbles', models.DecimalField(decimal_places=0, max_digits=4)),
                ('duels', models.DecimalField(decimal_places=0, max_digits=4)),
                ('duels_won', models.DecimalField(decimal_places=0, max_digits=4)),
                ('possession_lost_per_game', models.FloatField()),
                ('fouls_per_game', models.FloatField()),
                ('offsides_per_game', models.FloatField()),
                ('yellow_cards', models.DecimalField(decimal_places=0, max_digits=3)),
                ('red_cards', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ranking.Player')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ranking.Player')),
            ],
        ),
    ]
