# Generated by Django 3.0.1 on 2020-01-07 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='league_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='nationality',
            old_name='country_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='league',
            name='player',
        ),
        migrations.RemoveField(
            model_name='nationality',
            name='player',
        ),
        migrations.AddField(
            model_name='player',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ranking.League'),
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ranking.Nationality'),
        ),
    ]
