# Generated by Django 3.0.1 on 2020-01-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_auto_20200107_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('N', 'ST'), ('LS', 'LW'), ('PS', 'RW'), ('LP', 'LM'), ('PP', 'RM'), ('ŚPO', 'CAM'), ('Śp', 'CM'), ('ŚPD', 'CDM'), ('LO', 'LB'), ('PO', 'RB'), ('ŚO', 'CB'), ('BR', 'GK')], default='ST', max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='preferred_foot',
            field=models.CharField(choices=[('Lewa', 'left'), ('Prawa', 'right'), ('Obie', 'both')], default='right', max_length=5),
        ),
    ]
