# Generated by Django 3.0.1 on 2020-01-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_auto_20200109_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='goals_conceded_per_game',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='penalties_saved',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='saves_per_game',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='successful_saves_percent',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
