# Generated by Django 3.0.1 on 2020-01-11 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0006_auto_20200111_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='shots_per_game',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
