# Generated by Django 3.0.1 on 2020-01-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0009_auto_20200111_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('ST', 'N'), ('LS', 'LW'), ('PS', 'RW'), ('LP', 'LM'), ('PP', 'RM'), ('ŚPO', 'CAM'), ('Śp', 'CM'), ('ŚPD', 'CDM'), ('LO', 'LB'), ('PO', 'RB'), ('ŚO', 'CB'), ('BR', 'GK')], default='ST', max_length=3),
        ),
    ]
