# Generated by Django 3.0.1 on 2020-01-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0010_auto_20200111_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('ST', 'N'), ('LW', 'LS'), ('RW', 'PS'), ('LM', 'LP'), ('RM', 'PP'), ('CAM', 'ŚPO'), ('CM', 'ŚP'), ('CDM', 'ŚPD'), ('LB', 'LO'), ('RB', 'PO'), ('CB', 'ŚO'), ('GK', 'BR')], default='ST', max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='preferred_foot',
            field=models.CharField(choices=[('left', 'Lewa'), ('right', 'Prawa'), ('both', 'Obie')], default='right', max_length=5),
        ),
    ]
