# Generated by Django 3.0.1 on 2020-01-27 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0011_auto_20200111_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='crosses_per_game',
            new_name='accurate_passes_oposhalf_per_game',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='dribbles',
            new_name='big_chances_created',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='duels',
            new_name='clean_sheets',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='minutes_played',
            new_name='error_leading_to_shot',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='passes_per_game',
            new_name='fouled_per_game',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='possession_won_per_game',
            new_name='goals_per_game',
        ),
        migrations.AddField(
            model_name='player',
            name='minutes_per_game',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='player',
            name='touches_per_game',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='duels_won',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='successful_dribbles',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
